apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: ajay404/admin
          env:
          - name: PORT
            value: '3000'
          - name: NODE_ENV
            value: 'dev'
          - name: MONGO_URI
            value: 'mongodb://mongo-srv:27017/admin'
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: JWT_SECRET
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: SESSION_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: admin-srv
spec:
  selector:
    app: admin
  ports:
    - name: admin
      protocol: TCP
      port: 3000
      targetPort: 3000
