apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ajay404/auth
          env:
            - name: PORT
              value: '3000'
            - name: NODE_ENV
              value: 'dev'
            - name: JWT_EXPIRES_IN
              value: '1h'
            - name: MONGO_URI
              value: 'mongodb://mongo-srv:27017/auth'
            - name: DEFAULT_IMG_URL
              value: 'https://res.cloudinary.com/elevate-connect/image/upload/f_auto,q_auto/v1/elevate/xtt1vpogqccibkkc06oj'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: JWT_SECRET
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: SESSION_SECRET
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: EMAIL
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: APP_PASSWORD
            - name: ADMIN
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: ADMIN
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: ADMIN_PASSWORD
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudinary-secrets
                  key: CLOUDINARY_API_KEY
            - name: CLOUDINARY_API_SECRET
              valueFrom:
                  secretKeyRef:
                    name: cloudinary-secrets
                    key: CLOUDINARY_API_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
