apiVersion: apps/v1
kind: Deployment
metadata:
  name: founders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: founders
  template:
    metadata:
      labels:
        app: founders
    spec:
      containers:
        - name: founders
          image: ajay404/founders
          env:
          - name: PORT
            value: '3000'
          - name: NODE_ENV
            value: 'dev'
          - name: MONGO_URI
            value: 'mongodb://mongo-srv:27017/founders'
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: JWT_SECRET
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: SESSION_SECRET
          # - name: ELASTIC_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: elevate-es-elastic-user
          #       key: elastic
          - name: RAZORPAY_KEY_ID
            valueFrom:
              secretKeyRef:
                name: razorpay-secrets
                key: RAZORPAY_KEY_ID
          - name: RAZORPAY_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: razorpay-secrets
                key: RAZORPAY_KEY_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: founders-srv
spec:
  selector:
    app: founders
  ports:
    - name: founders
      protocol: TCP
      port: 3000
      targetPort: 3000
