apiVersion: apps/v1
kind: Deployment
metadata:
  name: investors-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: investors
  template:
    metadata:
      labels:
        app: investors
    spec:
      containers:
        - name: investors
          image: ajay404/investors
          env:
          - name: PORT
            value: '3000'
          - name: NODE_ENV
            value: 'dev'
          - name: MONGO_URI
            value: 'mongodb://mongo-srv:27017/investor'
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: JWT_SECRET
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: CLIENT_ID
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: SESSION_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: investors-srv
spec:
  selector:
    app: investors
  ports:
    - name: investors
      protocol: TCP
      port: 3000
      targetPort: 3000