apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: ajay404/search
          env:
          - name: PORT
            value: '3000'
          - name: NODE_ENV
            value: 'dev'
          - name: MONGO_URI
            value: 'mongodb://mongo-srv:27017/search'
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: JWT_SECRET
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: SESSION_SECRET
          # - name: ELASTIC_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: elevate-es-elastic-user
          #       key: elastic
---
apiVersion: v1
kind: Service
metadata:
  name: search-srv
spec:
  selector:
    app: search
  ports:
    - name: search
      protocol: TCP
      port: 3000
      targetPort: 3000
