apiVersion: apps/v1
kind: Deployment
metadata:
  name: startups-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: startups
  template:
    metadata:
      labels:
        app: startups
    spec:
      containers:
        - name: startups
          image: ajay404/startups
          env:
          - name: PORT
            value: '3000'
          - name: NODE_ENV
            value: 'dev'
          - name: MONGO_URI
            value: 'mongodb://mongo-srv:27017/startups'
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: JWT_SECRET
          - name: CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: CLIENT_ID
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: SESSION_SECRET
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elevate-es-elastic-user
                key: elastic
          - name: CLOUDINARY_CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: cloudinary-secrets
                key: CLOUDINARY_CLOUD_NAME
          - name: CLOUDINARY_API_KEY
            valueFrom:
              secretKeyRef:
                name: cloudinary-secrets
                key: CLOUDINARY_API_KEY
          - name: CLOUDINARY_API_SECRET
            valueFrom:
              secretKeyRef:
                name: cloudinary-secrets
                key: CLOUDINARY_API_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: startups-srv
spec:
  selector:
    app: startups
  ports:
    - name: startups
      protocol: TCP
      port: 3000
      targetPort: 3000
