version: '3'
services:
  users:
    container_name: users
    build:
      dockerfile: Dockerfile.dev
      context: ./users
    volumes:
      - /app/node_modules
      - ./users:/app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://users-db:27017
      - CLIENT_ID =136905288035-rfcs7jag9gh9e4ne4454jri50lec2p9s.apps.googleusercontent.com
      - JWT_SECRET = 'secretkeyhere'
  client:
    container_name: client
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - '4200:4200'
    volumes:
      - /app/node_modules
      - ./client:/app

  users-db:
    image: mongo:latest
    container_name: users-db
    ports:
      - '27017:27017'
    volumes:
      - ../data_elevate/db:/data/db
      
  
