version: '3'
services:
  auth:
    container_name: auth
    build:
      dockerfile: Dockerfile.dev
      context: ./auth
    volumes:
      - /app/node_modules
      - ./auth:/app
    ports:
      - '3000:3000'
    env_file:
      - ./auth/.env
  # client:
  #   container_name: client
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./client
  #   ports:
  #     - '4200:4200'
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app

  auth-db:
    image: mongo:latest
    container_name: auth-db
    ports:
      - '27017:27017'
    volumes:
      - ../data_elevate/db:/data/db
      
  
