name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'k8s/**'
jobs:     
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save elevate-cluster
      - run: kubectl apply -f k8s/stateless && kubectl apply -f k8s/ingress