name: deploy-ideas

on:
  push:
    branches:
      - master
    paths:
      - 'ideas/**'
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: cd ideas  && docker build -t ajay404/ideas .
      - run: docker push ajay404/ideas
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save elevate-cluster
      - run: kubectl rollout restart deployment ideas-depl  